version: "3.9"
services:
  # web:
  #     build: .
  #     ports:
  #         - "8000:80"
  #     depends_on:
  #         - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: myOwnSql
    # environment:
    #   SA_PASSWORD: "Your_password123"
    #   ACCEPT_EULA: "Y"
    env_file:
      - .env/db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
